//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFKP.Service_pra {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service_pra.IService_pra", CallbackContract=typeof(WPFKP.Service_pra.IService_praCallback))]
    public interface IService_pra {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService_pra/algorithm_fifo4")]
        void algorithm_fifo4(int[] row_page, int[] fifo4, string[] fifo5, int[] lru4, string[] lru5);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService_pra/algorithm_fifo4")]
        System.Threading.Tasks.Task algorithm_fifo4Async(int[] row_page, int[] fifo4, string[] fifo5, int[] lru4, string[] lru5);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_praCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService_pra/fifo4_callback")]
        void fifo4_callback(string[] result_fifo4, string[] result_fifo5, string[] result_lru4, string[] result_lru5);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_praChannel : WPFKP.Service_pra.IService_pra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_praClient : System.ServiceModel.DuplexClientBase<WPFKP.Service_pra.IService_pra>, WPFKP.Service_pra.IService_pra {
        
        public Service_praClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Service_praClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Service_praClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service_praClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service_praClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void algorithm_fifo4(int[] row_page, int[] fifo4, string[] fifo5, int[] lru4, string[] lru5) {
            base.Channel.algorithm_fifo4(row_page, fifo4, fifo5, lru4, lru5);
        }
        
        public System.Threading.Tasks.Task algorithm_fifo4Async(int[] row_page, int[] fifo4, string[] fifo5, int[] lru4, string[] lru5) {
            return base.Channel.algorithm_fifo4Async(row_page, fifo4, fifo5, lru4, lru5);
        }
    }
}
